name: Ertangi ob-havo

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch: {}

jobs:
  post-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni olish
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kutubxonalarni o'rnatish
        run: pip install requests

      - name: Ob-havoni joylash
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python weather_post.py
